/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vue;

import Modele.Case;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;


/**
 *
 * @author Dylan
 */
public class Fenetre extends JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        super();
        build();
        addWindowListener(new WindowAdapter() {
            public void windowsClosing(WindowEvent arg0) {
                super.windowClosing(arg0);
                System.exit(0);
            }
        });
    }
    
    public void build(){
        JMenuBar jm = new JMenuBar();
        JMenu m1 = new JMenu("Partie");
        JMenu m2 = new JMenu("Help");
        jm.add(m1);
        jm.add(m2);
        setJMenuBar(jm);
        
        setTitle("Jeu du Tetris");
        setSize(450,500);
        JComponent principal = new JPanel(new BorderLayout());
        JComponent plateau = new JPanel(new GridLayout(20,10));
       
        Border blackline = BorderFactory.createLineBorder(Color.black,1);

        for (int i = 0; i<200;i++){
            JComponent ptest = new Case();
            ptest.setBorder(blackline);
            plateau.add(ptest);
        }
         principal.add(plateau, "Center");
        
        JComponent Bouttons = new JPanel(new FlowLayout());
        Button gauche = new Button("Gauche");
        Button droite = new Button("Droite");
        Button bas = new Button("Bas");
        Button tourner = new Button("Tourner");
        Bouttons.add(gauche);
        Bouttons.add(droite);
        Bouttons.add(bas);
        Bouttons.add(tourner);
        principal.add(Bouttons,"East");
        
        principal.setBorder(blackline);
        add(principal);
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
